name: README update

on:
  workflow_dispatch:
  schedule:
    # nightly at 5:30am
    - cron: '30 5 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: sync README
        run:  make sync

